# stolen from https://github.com/conda/conda-recipes/tree/master/matplotlib
# selectors [py27] and comments need to be `# [selector] comment` not `[sel] # comment`

package:
  name: matplotlib
  # Increase to prevent additional builds -> can be set after the first package is build and then repushed...
  version: 1.5.0+532.g3d942f7.dirty

source:
  git_url: git://github.com/janschulz/matplotlib
  git_rev: master

  patches:
    # don't run nosetest
    - cfg_notests.patch
    # nake Qt4Agg the default backend
    - cfg_qt4agg.patch    [not osx]
    - rctmp_pyside.patch  [not osx]
    # tk work on OSX
    - osx-tk.patch        [osx]
    # dynamic version from git
    - condaversion.patch

requirements:
  build:
    - python
    - setuptools
    - numpy
    - python-dateutil
    - freetype >=2.5,<2.6
    - pyparsing
    - pytz
    - py2cairo           #[linux and py2k]
    - tornado
    - libpng
    - zlib                [win]
    # msinttypes is from the conda-forge or janschulz channel!
    - msinttypes          [win]
    - pyqt                [not osx]
    - cycler
    - tk
     # this is currently only available in my channel
    - functools32         [py2k]

  run:
    - python
    - numpy
    - python-dateutil
    - freetype            [unix]
    - pytz
    - pyparsing
    - py2cairo           #[linux and py2k]
    - libpng              [unix]
    - pyqt                [not osx]
    - cycler
    - tk
    - functools32         [py2k]

test:
  requires:
    - nose
    - mock

about:
  home: http://matplotlib.sourceforge.net/
  license: PSF-based (http://matplotlib.sourceforge.net/users/license.html)
