package:
  name: ipyext
  version: 0.1.0

source:
  git_url: https://github.com/ipython-contrib/IPython-extensions.git
  git_tag: v0.1.0

requirements:
  build:
    - python
    - pypandoc # comes from our own channel
    - ipython
    - setuptools

  run:
    - python
    - ipython   
  
about:
  home: https://github.com/ipython-contrib/IPython-extensions/
  license: BSD
  license_file: COPYING.rst
  summary: 'IPython-extensions: more magic(s) for IPython'

