package:
  name: pypandoc
  version: 1.1.1

source:
  git_url: https://github.com/bebraw/pypandoc.git
  git_tag: v1.1.1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

build:
  script_env:
    - PYPI_USER
    - PYPI_PASS
    
test:
  imports:
    - pypandoc
  
about:
  home: https://github.com/bebraw/pypandoc
  license: MIT
  summary: 'Thin wrapper for "pandoc"'

