package:
  name: pep8
  version: "0.7.1"

source:
  git_url: https://github.com/myint/docformatter.git
  git_tag: v0.7.1

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - docformatter

about:
  home: https://github.com/myint/docformatter
  license : MIT License