package:
  name: untokenize
  version: "0.1.1"

source:
  git_url: https://github.com/myint/untokenize.git
  git_tag: v0.1.1

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - untokenize

about:
  home: https://github.com/myint/untokenize
  license : MIT License