package:
  name: pep8radius
  version: "0.9.2"

source:
  git_url: https://github.com/hayd/pep8radius.git
  git_tag: v0.9.2

build:
  number: 0

requirements:
  build:
    - python
    - pep8
    - docformatter
    - yapf
    - colorama

  run:
    - python
    - pep8
    - docformatter
    - yapf
    - colorama

test:
  imports:
    - pep8radius

about:
  home: https://github.com/hayd/pep8radius
  license : MIT License