package:
  name: pytest
  version: "2.8.7"

source:
  git_url: https://github.com/pytest-dev/pytest.git
  git_tag: "2.8.7"

build:
  number: 0

requirements:
  build:
    - python
    - py  >=1.4.29
    - colorama # [win]

  run:
    - python
    - py  >=1.4.29
    - colorama # [win]


about:
  home: https://github.com/pytest-dev/pytest
  summary: 'simple powerful testing with Python'
  license : MIT license
