package:
  name: pep8
  version: "1.7.0"

source:
  git_url: https://github.com/PyCQA/pep8.git
  git_tag: "1.7.0"

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - pep8

about:
  home: https://github.com/PyCQA/pep8
  license : Expat License