package:
  name: autopep8
  version: "1.2.1"

source:
  git_url: https://github.com/hhatto/autopep8.git
  git_tag: ver1.2.1

build:
  number: 0

requirements:
  build:
    - python
    - pep8

  run:
    - python
    - pep8

test:
  imports:
    - autopep8

about:
  home: https://github.com/hhatto/autopep8
  license : MIT License