package:
  name: pies2overrides
  version: "2.6.3"

source:
  fn: pies2overrides-2.6.7.tar.gz
  url: https://pypi.python.org/packages/source/p/pies2overrides/pies2overrides-2.6.7.tar.gz
  md5: d475a3c4a85669bc8c85253bf1287f96

build:
  number: 0
  
requirements:
  build:
    - python  2.7.*
    - ipaddress

  run:
    - python  2.7.*
    - ipaddress

about:
  home: https://github.com/timothycrosley/pies
  license : MIT License