package:
  name: yapf
  version: "0.6.2"

source:
  git_url: https://github.com/google/yapf.git
  git_tag: v0.6.2

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - yapf

about:
  home: https://github.com/google/yapf
  license : Apache License v2.0