package:
  name: cdiff
  version: "0.9.8"

source:
  git_url: https://github.com/ymattw/cdiff.git
  git_tag: "0.9.8"

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - cdiff

about:
  home: https://github.com/ymattw/cdiff
  license : BSD-3